##
## EPITECH PROJECT, 2022
## arcade_graphics
## File description:
## Makefile
##

all:
	make -C sfml
	make -C ncurses
	make -C sdl2

clean:
	make clean -C sfml
	make clean -C ncurses
	make clean -C sdl2

fclean:
	make fclean -C sfml
	make fclean -C ncurses
	make fclean -C sdl2


re: fclean all
