##
## EPITECH PROJECT, 2022
## arcade_games
## File description:
## Makefile
##

all:
	make -C menu
	make -C pacman
	make -C nibbler

clean:
	make clean -C pacman
	make clean -C nibbler
	make clean -C menu

fclean:
	make fclean -C pacman
	make fclean -C nibbler
	make fclean -C menu


re: fclean all